apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-release
  labels:
    app: dms-release
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dms-release
  template:
    metadata:
      labels:
        app: dms-release
    spec:
      containers:
        - name: dms-chatting
          image: "{{ .Values.dmsChatting.image.repository }}:{{ .Values.dmsChatting.image.tag }}"
          ports:
            - containerPort: {{ .Values.dmsChatting.containerPort }}
        - name: dms-bulletin
          image: "{{ .Values.dmsBulletin.image.repository }}:{{ .Values.dmsBulletin.image.tag }}"
          ports:
            - containerPort: {{ .Values.dmsBulletin.containerPort }}

