apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: dms-bulletin-container
          image: {{ .Values.bulletinImage }}
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
        - name: dms-chatting-container
          image: {{ .Values.chattingImage }}
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
        - name: dms-gateway-container
          image: {{ .Values.gatewayImage }}
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
            - name: BULLETIN_IP
              value: {{ .Values.bulletinIp }}
            - name: CHATTING_IP
              value: {{ .Values.chattingIp }}

