apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namesapce }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: dms-bulletin-container
          image: {{ .Values.bulletinImage }}:{{ .Values.bulletinImageTag }}
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
          resources:
            requests:
              cpu: {{ .Values.bulletinRequestCpu }}
            limits:
              cpu: {{ .Values.bulletinMaxCpu }}
        - name: dms-chatting-container
          image: {{ .Values.chattingImage }}:{{ .Values.chattingImageTag }}
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
          resources:
            requests:
              cpu: {{ .Values.chattingRequestCpu }}
            limits:
              cpu: {{ .Values.chattingMaxCpu }}
        - name: dms-gateway-container
          image: {{ .Values.gatewayImage }}:{{ .Values.gatewayImageTag }}
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: {{ .Values.mysqlUrl }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysqlUsername }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
            - name: BULLETIN_IP
              value: {{ .Values.bulletinIp }}
            - name: CHATTING_IP
              value: {{ .Values.chattingIp }}
          resources:
            requests:
              cpu: {{ .Values.gatewayRequestCpu }}
            limits:
              cpu: {{ .Values.gatewayMaxCpu }}
