apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http-gateway
      protocol: TCP
      port: {{ .Values.gatewayPort }}
      targetPort: {{ .Values.gatewayTargetPort }}   # Gateway 컨테이너로 전달
    - name: http-bulletin
      protocol: TCP
      port: {{ .Values.bulletinPort }}
      targetPort: {{ .Values.bulletinTargetPort }}   # Bulletin 컨테이너로 전달
    - name: http-chatting
      protocol: TCP
      port: {{ .Values.chattingPort }}
      targetPort: {{ .Values.chattingTargetPort }}   # Chatting 컨테이너로 전달
  type: {{ .Values.serviceType }}

