apiVersion: v1
kind: Service
metadata:
  name: dms-release-service
spec:
  selector:
    app: dms-release
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}

