#도커 이미지 태그 관리
bulletinImageTag: ca819079851f9195674bbe71bbb7e0b95b0e83eb
chattingImageTag: ca819079851f9195674bbe71bbb7e0b95b0e83eb
gatewayImageTag: ca819079851f9195674bbe71bbb7e0b95b0e83eb

#공통
namespace: default

#deployment 설정
deploymentName: dms-comm-deployment
replicaCount: 1 

gatewayRequestCpu: 200m
gatewayMaxCpu: 1
bulletinRequestCpu: 200m
bulletinMaxCpu: 1
chattingRequestCpu: 200m
chattingMaxCpu: 1

mysqlUrl: "jdbc:mysql://dms-database.ch0icwqe8sr2.us-east-1.rds.amazonaws.com:3306/comm"
mysqlUsername: "admin"
mysqlPassword: "bs135800"

bulletinImage: "kyoona/dms-bulletin"
chattingImage: "kyoona/dms-chatting"
gatewayImage: "kyoona/dms-gateway"

bulletinIp: "http://dms-comm-service:8081"
chattingIp: "http://dms-comm-service:8082"

# Ingress 설정
ingressName: dms-comm-ingress
namespace: default
serviceName: dms-comm-service
servicePort: 80

# Service 설정
serviceName: dms-comm-service
appName: dms-comm

gatewayPort: 80
gatewayTargetPort: 8080

bulletinPort: 8081
bulletinTargetPort: 8081

chattingPort: 8082
chattingTargetPort: 8082

serviceType: ClusterIP

#hpa 설정
hpa:
  name: dm-comms-hpa
  namespace: default
  targetDeployment: dms-comm-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    cpu:
      targetUtilization: 100
  behavior:
    scaleDown:
      stabilizationSeconds: 30
