# Deployment 설정
deploymentName: dms-comm
replicaCount: 2

mysqlUrl: "jdbc:mysql://dms-database.ch0icwqe8sr2.us-east-1.rds.amazonaws.com:3306/comm"
mysqlUsername: "admin"
mysqlPassword: "bs135800"

bulletinImage: "kyoona/dms-bulletin"
chattingImage: "kyoona/dms-chatting"
gatewayImage: "kyoona/dms-gateway"

bulletinIp: "http://dms-comm-service:8081"
chattingIp: "http://dms-comm-service:8082"

# Ingress 설정
ingressName: comm-ingress
namespace: default
serviceName: dms-comm-service
servicePort: 80

# Service 설정
serviceName: dms-comm-service
appName: dms-comm

gatewayPort: 80
gatewayTargetPort: 8080

bulletinPort: 8081
bulletinTargetPort: 8081

chattingPort: 8082
chattingTargetPort: 8082

serviceType: ClusterIP

