apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-comm-deployment
  labels:
    app: dms-comm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dms-comm
  template:
    metadata:
      labels:
        app: dms-comm
    spec:
      containers:
        - name: dms-bulletin-container
          image: kyoona/dms-bulletin
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://dms-database.ch0icwqe8sr2.us-east-1.rds.amazonaws.com:3306/comm"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "bs135800"
        - name: dms-chatting-container
          image: kyoona/dms-chatting
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://dms-database.ch0icwqe8sr2.us-east-1.rds.amazonaws.com:3306/comm"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "bs135800"
        - name: dms-gateway-container
          image: kyoona/dms-gateway
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://dms-database.ch0icwqe8sr2.us-east-1.rds.amazonaws.com:3306/comm"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "bs135800"
            - name: BULLETIN_IP
              value: "http://dms-comm-service:8081"
            - name: CHATTING_IP
              value: "http://dms-comm-service:8082"
